export let projects = [
  {
    id: "1",
    name: "Wahrheitsschwestern",
    location: "-",
    dates: "-",
    description: "Wahrheitsschwestern Beschreibung",
    folder: "wahrheitsschwestern",
    mainImg: { url: "wahrheitsschwestern_main.jpeg", alt: "" },
    images: [
      { url: "wahrheitsschwestern_1.jpg", alt: "" },
      { url: "wahrheitsschwestern_2.jpg", alt: "" },
      { url: "wahrheitsschwestern_4.jpg", alt: "" },
      { url: "wahrheitsschwestern_5.jpg", alt: "" },
      { url: "wahrheitsschwestern_3.jpg", alt: "" },
    ],
  },
  {
    id: "2",
    name: "Träumen",
    location: "-",
    dates: "-",
    description: "Träumen Beschreibung",
    folder: "traeumen",
    mainImg: { url: "traeumen_main.jpg", alt: "" },
    images: [
      { url: "traeumen_3.jpg", alt: "" },
      { url: "traeumen_2.jpg", alt: "" },
      { url: "traeumen_1.jpg", alt: "" },
      { url: "traeumen_5.jpg", alt: "" },
      { url: "traeumen_4.jpg", alt: "" },
    ],
  },
  {
    id: "3",
    name: "peer gynt",
    location: "-",
    dates: "-",
    description: "peer gynt Beschreibung",
    folder: "peer",
    mainImg: { url: "peer_main.jpeg", alt: "" },
    images: [
      { url: "peer_1.jpg", alt: "" },
      { url: "peer_2.jpg", alt: "" },
      { url: "peer_3.jpg", alt: "" },
      { url: "peer_4.jpg", alt: "" },
      { url: "peer_5.jpg", alt: "" },
      { url: "peer_6.jpg", alt: "" },
      { url: "peer_7.jpg", alt: "" },
      { url: "peer_8.jpg", alt: "" },
    ],
  },
];
