export let projects = [
    {
    id: "1",
    name: "0800/1110333",
    location: "Stellwerk e.V. Weimar",
    dates: "Premiere: 23.02.2019",
    description: "Regie: Tanja Linnekogel\nBühnen-und Kostümbild: Sara Drasdo",
    folder: "0800",
    mainImg: { url: "0800_main.jpeg", alt: "" },
    images: [
      { url: "0800_1.jpg", alt: "" },
      { url: "0800_2.jpg", alt: "" },
      { url: "0800_3.jpg", alt: "" },
      { url: "0800_4.jpg", alt: "" },
    ],
  },
    {
    id: "2",
    name: "Peer Gynt",
    location: "Stellwerk e.V. Weimar",
    dates: "Premiere: 28.06.2019 ",
    description: "Regie: Bastian Heidenreich und Stephan Mahn\nBühne: Philipp Münnich\nKostüme: Sara Drasdo",
    folder: "peer",
    mainImg: { url: "peer_main.jpeg", alt: "" },
    images: [
      { url: "peer_1.jpg", alt: "" },
      { url: "peer_2.jpg", alt: "" },
      { url: "peer_3.jpg", alt: "" },
      { url: "peer_4.jpg", alt: "" },
      { url: "peer_5.jpg", alt: "" },
      { url: "peer_6.jpg", alt: "" },
      { url: "peer_7.jpg", alt: "" },
      { url: "peer_8.jpg", alt: "" },
    ],
  },
    {
    id: "3",
    name: "Die Wahrheitsschwestern (Uraufführung)",
    location: "Hochschule für Musik Weimar",
    dates: "Premiere: 25.10.2019 ",
    description: "Regie: Eszter Johanna Barta\nMusikalische Leitung: Giordano Bruno do Nascimento\nBühne: Elif Zengin\nKostüme: Sara Drasdo",
    folder: "wahrheitsschwestern",
    mainImg: { url: "wahrheitsschwestern_main.jpeg", alt: "" },
    images: [
      { url: "wahrheitsschwestern_1.jpg", alt: "" },
      { url: "wahrheitsschwestern_2.jpg", alt: "" },
      { url: "wahrheitsschwestern_4.jpg", alt: "" },
      { url: "wahrheitsschwestern_5.jpg", alt: "" },
      { url: "wahrheitsschwestern_3.jpg", alt: "" },
    ],
  },
    {
    id: "4",
    name: "Es war Einmal",
    location: "Stellwerk e.V. Weimar",
    dates: "Premiere: 26.10.2019 ",
    description: "Regie: Vincent Kresse\nBühne und Kostüm: Sara Drasdo",
    folder: "einmal",
    mainImg: { url: "einmal_main.jpeg", alt: "" },
    images: [
      { url: "einmal_1.jpg", alt: "" },
      { url: "einmal_2.jpg", alt: "" },
      { url: "einmal_5.jpg", alt: "" },
      { url: "einmal_4.jpg", alt: "" },
      { url: "einmal_3.jpg", alt: "" },
    ],
  },
  {
    id: "5",
    name: "438 Tage NSU-Prozess - Eine theatrale Spurensuche",
    location: "Kunstfest Weimar in Kooperation mit dem DNT Weimar",
    dates: "Premiere: 25.08.2021",
    description: "Regie: Nuran David Calis\nBühne: Irina Schicketanz\nKostüme: Sara Drasdo\nMusik: Vivan Bhatti",
    folder: "nsu",
    mainImg: { url: "nsu_main.jpg", alt: "" },
    images: [
      { url: "nsu_1.jpg", alt: "" },
      { url: "nsu_2.jpg", alt: "" },
      { url: "nsu_3.jpg", alt: "" },
      { url: "nsu_4.jpg", alt: "" },
    ],
  },
  {
    id: "6",
    name: "Mutter",
    location: "Hochschule für Musik Weimar",
    dates: "Premiere: 01.10.2021",
    description: "Regie: Eszter Johanna Barta\nMusikalische Leitung: Giordano Bruno do Nascimento\nLibretto: Romina Nikolic\nBühnen- und Kostümbild: Sara Drasdo",
    folder: "mutter",
    mainImg: { url: "mutter_main.jpeg", alt: "" },
    images: [
      { url: "mutter_2.jpg", alt: "" },
      { url: "mutter_1.jpg", alt: "" },
      { url: "mutter_3.jpg", alt: "" },
      { url: "mutter_4.jpg", alt: "" },
      { url: "mutter_5.jpg", alt: "" },
      { url: "mutter_6.jpg", alt: "" },
      { url: "mutter_7.jpg", alt: "" },
    ],
  },
  {
    id: "7",
    name: "Kreuzen und Queren",
    location: "Online",
    dates: "Online Premiere: 07.10.2021",
    description: "Eine digitale Werkschau des B:Clubs+ Schauspiel\nEine Produktion der Bürgerbühne, Staatsschauspiel Dresden\nRegie, Konzeption, Drehbuch: Ursula Hobmair, Simon Werdelis\nKostüme: Sara Drasdo",
    folder: "",
    mainImg: { url: "", alt: "" },
    images: [
    ],
  },
  {
    id: "8",
    name: "Our Legacy - Ostdeutsche Geschichte(n) of Color",
    location: "Beim Montagscafè Staatsschauspiel Dresden am 18.10.2021",
    dates: "Im E-Werk DNT Weimar am 05.11.2021",
    description: "Ein polyphoner Gesprächsabend von und mit Katharina Warda\nBühne/Maske: Sara Drasdo ",
    folder: "",
    mainImg: { url: "", alt: "" },
    images: [
    ],
  },
  {
    id: "9",
    name: "Man wird ja wohl noch träumen dürfen",
    location: "Stellwerk e.V. Weimar",
    dates: "Premiere: 14.07.2022 ",
    description: "Regie: Debora Willing-Gäbler\nBühne und Kostüme: Sara Drasdo",
    folder: "traeumen",
    mainImg: { url: "traeumen_main.jpg", alt: "" },
    images: [
      { url: "traeumen_1.jpg", alt: "" },
      { url: "traeumen_2.jpg", alt: "" },
      { url: "traeumen_3.jpg", alt: "" },
      { url: "traeumen_4.jpg", alt: "" },
      { url: "traeumen_5.jpg", alt: "" },
    ],
  },

];

export let dates = [
  {
    date: "18.11.2022",
    title: "Premiere Anti-Liebestrank (Uraufführung)",
    location: "Mon Ami Weimar",
  },
  {
    date: "26.01.2023",
    title: "Premiere Kuckuck im Koffer",
    location: "Deutsches Nationaltheater Weimar",
  },
];
