export let projects = [
  {
    id: "1",
    name: "Wahrheitsschwestern",
    location: "-",
    dates: "-",
    description: "Wahrheitsschwestern Beschreibung",
    folder: "wahrheitsschwestern",
    mainImg: { url: "wahrheitsschwestern_main.jpeg", alt: "" },
    images: [
      { url: "wahrheitsschwestern_1.jpg", alt: "" },
      { url: "wahrheitsschwestern_2.jpg", alt: "" },
      { url: "wahrheitsschwestern_4.jpg", alt: "" },
      { url: "wahrheitsschwestern_5.jpg", alt: "" },
      { url: "wahrheitsschwestern_3.jpg", alt: "" },
    ],
  },
  {
    id: "2",
    name: "Träumen",
    location: "-",
    dates: "-",
    description: "Träumen Beschreibung",
    folder: "traeumen",
    mainImg: { url: "traeumen_main.jpg", alt: "" },
    images: [
      { url: "traeumen_3.jpg", alt: "" },
      { url: "traeumen_2.jpg", alt: "" },
      { url: "traeumen_1.jpg", alt: "" },
      { url: "traeumen_5.jpg", alt: "" },
      { url: "traeumen_4.jpg", alt: "" },
    ],
  },
  {
    id: "3",
    name: "peer gynt",
    location: "-",
    dates: "-",
    description: "peer gynt Beschreibung",
    folder: "peer",
    mainImg: { url: "peer_main.jpeg", alt: "" },
    images: [
      { url: "peer_1.jpg", alt: "" },
      { url: "peer_2.jpg", alt: "" },
      { url: "peer_3.jpg", alt: "" },
      { url: "peer_4.jpg", alt: "" },
      { url: "peer_5.jpg", alt: "" },
      { url: "peer_6.jpg", alt: "" },
      { url: "peer_7.jpg", alt: "" },
      { url: "peer_8.jpg", alt: "" },
    ],
  },
  {
    id: "4",
    name: "NSU",
    location: "-",
    dates: "-",
    description: "NSU Beschreibung",
    folder: "nsu",
    mainImg: { url: "nsu_main.jpg", alt: "" },
    images: [
      { url: "nsu_1.jpg", alt: "" },
      { url: "nsu_2.jpg", alt: "" },
      { url: "nsu_3.jpg", alt: "" },
      { url: "nsu_4.jpg", alt: "" },
    ],
  },
  {
    id: "5",
    name: "Mutter",
    location: "-",
    dates: "-",
    description: "Mutter Beschreibung",
    folder: "mutter",
    mainImg: { url: "mutter_main.jpeg", alt: "" },
    images: [
      { url: "mutter_2.jpg", alt: "" },
      { url: "mutter_1.jpg", alt: "" },
      { url: "mutter_3.jpg", alt: "" },
      { url: "mutter_4.jpg", alt: "" },
      { url: "mutter_5.jpg", alt: "" },
      { url: "mutter_6.jpg", alt: "" },
      { url: "mutter_7.jpg", alt: "" },
    ],
  },
  {
    id: "6",
    name: "Es war Einmal",
    location: "-",
    dates: "-",
    description: "Es war Einmal Beschreibung",
    folder: "einmal",
    mainImg: { url: "einmal_main.jpeg", alt: "" },
    images: [
      { url: "einmal_1.jpg", alt: "" },
      { url: "einmal_2.jpg", alt: "" },
      { url: "einmal_5.jpg", alt: "" },
      { url: "einmal_4.jpg", alt: "" },
      { url: "einmal_3.jpg", alt: "" },
    ],
  },
  {
    id: "7",
    name: "B Club",
    location: "-",
    dates: "-",
    description: "B Club Schauspiel Beschreibung",
    folder: "bclub",
    mainImg: { url: "bclub_main.jpeg", alt: "" },
    images: [
      { url: "bclub_1.jpg", alt: "" },
      { url: "bclub_2.jpg", alt: "" },
      { url: "bclub_3.jpg", alt: "" },
      { url: "bclub_4.jpg", alt: "" },
      { url: "bclub_5.jpg", alt: "" },
      { url: "bclub_6.jpg", alt: "" },
      { url: "bclub_7.jpg", alt: "" },
    ],
  },
  {
    id: "8",
    name: "0800",
    location: "-",
    dates: "-",
    description: "0800 Beschreibung",
    folder: "0800",
    mainImg: { url: "0800_main.jpeg", alt: "" },
    images: [
      { url: "0800_1.jpg", alt: "" },
      { url: "0800_2.jpg", alt: "" },
      { url: "0800_3.jpg", alt: "" },
      { url: "0800_4.jpg", alt: "" },
    ],
  },
];
